name: Auto Dating Push Notifications

on:
  schedule:
    - cron: '30 8 * * *'   # 2:00 PM IST
    - cron: '30 13 * * *'  # 7:00 PM IST
    - cron: '0 17 * * *'   # 10:30 PM IST
  workflow_dispatch:

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Firebase Admin
        run: pip install firebase-admin

      - name: Send Auto Push Notification
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: python send_push.py
